# Generated by Django 5.0.3 on 2024-03-12 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("description", models.TextField()),
                ("link", models.CharField(default="", max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Merchant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
                ("logo", models.URLField(default="")),
                ("bannar", models.URLField(default="")),
                ("image_urls", models.JSONField(default=dict)),
                ("final_terms_condition", models.TextField()),
                ("report_storename", models.CharField(max_length=500)),
                ("is_custom_override_case", models.BooleanField(default=False)),
                ("intermediate_page_text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("card_type", models.BooleanField(default=False)),
                ("product_label", models.CharField(blank=True, max_length=500)),
                ("product_description", models.JSONField(default=dict)),
                ("varients", models.JSONField(default=dict)),
                ("image_url", models.URLField(default="")),
                ("image_urls", models.JSONField(default=dict)),
                (
                    "brochure_files",
                    models.FileField(blank=True, null=True, upload_to="brochures/"),
                ),
                ("cashback_url", models.URLField(default="")),
                ("is_compared", models.BooleanField(default=False)),
                ("brand", models.CharField(max_length=500)),
                ("offer_type", models.CharField(max_length=500)),
                ("coupons_count", models.IntegerField(default=0)),
                ("secondary_cashback_count", models.IntegerField(default=0)),
                ("basePrice", models.JSONField(default=dict)),
                (
                    "rating",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("rating_count", models.IntegerField(default=0)),
                ("review_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("redirect_count", models.IntegerField(default=0)),
                (
                    "products_compared",
                    models.ManyToManyField(blank=True, default="", to="api.product"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("discount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("cashback", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(max_length=10)),
                ("start_date", models.DateField(auto_now=True)),
                ("end_date", models.DateField()),
                (
                    "Merchant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.merchant"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="api.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="merchant_offer",
            field=models.ManyToManyField(
                blank=True,
                default="",
                related_name="merchant_offer",
                to="api.productoffer",
            ),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=500)),
                ("description", models.TextField()),
                ("link", models.CharField(default="", max_length=500)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.category"
                    ),
                ),
            ],
        ),
    ]
