# Generated by Django 5.0.3 on 2024-03-13 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_product_card_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("link", models.CharField(max_length=500)),
                ("logo", models.URLField(default="")),
                ("bannar", models.URLField(default="")),
                ("image_urls", models.JSONField(default=dict)),
                ("short_description", models.TextField()),
                ("cashback_type", models.CharField(max_length=500)),
                ("full_description", models.TextField()),
                ("storeName", models.CharField(max_length=500)),
                ("seo_description", models.TextField()),
                (
                    "rating_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("rating_count", models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="bannar",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="final_terms_condition",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="image_urls",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="intermediate_page_text",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="is_custom_override_case",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="logo",
        ),
        migrations.RemoveField(
            model_name="merchant",
            name="report_storename",
        ),
        migrations.AddField(
            model_name="merchant",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merchants",
                to="api.store",
            ),
        ),
    ]
