# Generated by Django 5.0.3 on 2024-03-13 03:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_store_remove_merchant_bannar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="store",
            name="image_urls",
        ),
    ]
