# Generated by Django 5.0.3 on 2024-03-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_store_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="link",
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
