# Generated by Django 5.0.3 on 2024-03-13 04:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_merchant_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="products_compared",
        ),
    ]
