# Generated by Django 5.0.3 on 2024-03-13 04:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_remove_product_products_compared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="merchant_offer",
        ),
        migrations.AddField(
            model_name="product",
            name="merchant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="api.merchant",
            ),
        ),
    ]
