# Generated by Django 5.0.3 on 2024-03-13 04:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_remove_product_merchant_offer_product_merchant"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="coupons_count",
        ),
        migrations.RemoveField(
            model_name="product",
            name="secondary_cashback_count",
        ),
    ]
