# Generated by Django 5.0.3 on 2024-03-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_remove_product_coupons_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="link",
            field=models.CharField(default="", max_length=500),
        ),
    ]
