# Generated by Django 5.0.3 on 2024-03-13 04:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0013_alter_product_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="product_label",
        ),
    ]
