# Generated by Django 5.0.3 on 2024-03-14 03:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_remove_product_product_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="productoffer",
            old_name="Merchant",
            new_name="merchant",
        ),
    ]
