# Generated by Django 5.0.3 on 2024-03-14 03:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_rename_merchant_productoffer_merchant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productoffer",
            name="end_date",
            field=models.DateField(null=True),
        ),
    ]
