# Generated by Django 5.0.3 on 2024-03-14 03:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_alter_productoffer_end_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productoffer",
            name="merchant",
        ),
    ]
