# Generated by Django 5.0.3 on 2024-03-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0017_remove_productoffer_merchant"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="display_category",
            field=models.BooleanField(default=True),
        ),
    ]
