# Generated by Django 4.2.5 on 2024-05-20 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_category_display_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("mobile_no", models.CharField(max_length=15)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BusinessRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gstin_choice",
                    models.CharField(
                        choices=[
                            ("I Have GSTIN Number", "I Have GSTIN Number"),
                            (
                                "I Want To Sell Products That Exempt GSTIN",
                                "I Want To Sell Products That Exempt GSTIN",
                            ),
                            (
                                "I Don't Have GSTIN Number OR I Have Applied For GSTIN",
                                "I Don't Have GSTIN Number OR I Have Applied For GSTIN",
                            ),
                        ],
                        max_length=54,
                    ),
                ),
                ("business_name", models.CharField(default="", max_length=255)),
                ("pan_number", models.CharField(default="", max_length=10)),
                ("business_type", models.CharField(default="", max_length=100)),
                (
                    "business_email",
                    models.EmailField(
                        blank=True, default="", max_length=254, null=True
                    ),
                ),
                (
                    "business_mobile_number",
                    models.CharField(blank=True, default="", max_length=15, null=True),
                ),
                ("address_line_1", models.CharField(default="", max_length=255)),
                (
                    "address_line_2",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("state", models.CharField(default="", max_length=100)),
                ("city", models.CharField(default="", max_length=100)),
                ("pincode", models.CharField(default="", max_length=6)),
                (
                    "gstin",
                    models.CharField(blank=True, default="", max_length=15, null=True),
                ),
                (
                    "signature_image",
                    models.ImageField(
                        blank=True, default="", null=True, upload_to="signatures/"
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bank_ifsc_code",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "bank_account_holder_name",
                    models.CharField(default="", max_length=20),
                ),
                ("bank_account_type", models.CharField(default="", max_length=20)),
                ("store_display_name", models.CharField(default="", max_length=20)),
                ("primary_category", models.CharField(default="", max_length=30)),
                ("store_disc", models.TextField(default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="api.customuser"
                    ),
                ),
            ],
        ),
    ]
