# Generated by Django 4.2.5 on 2024-05-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0020_customuser_groups_customuser_is_superuser_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
